import os
import sys
import asyncio
import json

sys.path.append(os.path.join(os.path.dirname(__file__), "..", "backend"))
from main import generate_single_draft, llm_client, SingleRecipeResponse

async def run_analysis():
    dishes = [
        "Shepherd's Pie",
        "Coq au Vin",
        "Clam Chowder",
        "Chicken Cordon Bleu",
        "Beef Wellington",
        "Ratatouille",
        "Hungarian Goulash",
        "Jambalaya",
        "Chicken Parmesan",
        "Moussaka"
    ]
    
    results = {}
    for dish_name in dishes:
        print(f"🕵️‍♂️ Running LLM Jury for: '{dish_name}'...")
        # 1. Generate 3 independent drafts
        drafts = await asyncio.gather(
            asyncio.to_thread(generate_single_draft, dish_name),
            asyncio.to_thread(generate_single_draft, dish_name),
            asyncio.to_thread(generate_single_draft, dish_name)
        )
        
        # 2. Run the Judge
        drafts_text = "\n\n".join([f"Draft {i+1}:\n{d.model_dump_json(indent=2)}" for i, d in enumerate(drafts)])
        judge_prompt = f"""We need the ultimate golden baseline recipe for '{dish_name}'.
        
Here are 3 independent drafts generated by our baseline recipe AI:

{drafts_text}

INSTRUCTIONS:
1. Analyze the 3 drafts. Identify the most statistically sound, common-sense golden baseline values.
2. If one draft hallucinates a weird ingredient, ignore it.
3. Average or pick the most credible ingredient weights and portion sizes.
4. Output the final, synthesized golden baseline recipe.
"""
        def run_judge():
            completion = llm_client.beta.chat.completions.parse(
                model="gpt-4o-mini",
                messages=[
                    {"role": "system", "content": "You are the head judge of a nutrition AI jury."},
                    {"role": "user", "content": judge_prompt}
                ],
                response_format=SingleRecipeResponse,
                temperature=0.0
            )
            return completion.choices[0].message.parsed.recipe

        final_recipe = await asyncio.to_thread(run_judge)
        results[dish_name] = final_recipe.model_dump()
        print(f"✅ Finished: {dish_name}")
        
    with open("jury_10_dishes.json", "w") as f:
        json.dump(results, f, indent=2)
    print("Done! Saved to jury_10_dishes.json")
    
if __name__ == "__main__":
    asyncio.run(run_analysis())
