import os
import sys
import asyncio
import json

sys.path.append(os.path.join(os.path.dirname(__file__), "..", "backend"))
from main import generate_single_draft, llm_client, SingleRecipeResponse

async def run_analysis():
    dish_name = "Cheesecake"
    print(f"🕵️‍♂️ Running LLM Jury Analysis for: '{dish_name}'\n")
    
    # 1. Generate 3 independent drafts
    drafts = await asyncio.gather(
        asyncio.to_thread(generate_single_draft, dish_name),
        asyncio.to_thread(generate_single_draft, dish_name),
        asyncio.to_thread(generate_single_draft, dish_name)
    )
    
    for i, draft in enumerate(drafts):
        print(f"--- DRAFT {i+1} ---")
        print(f"Ingredients: {draft.ingredients_text}")
        print(f"Serving: {draft.serving_size}\n")
        
    # 2. Run the Judge
    drafts_text = "\n\n".join([f"Draft {i+1}:\n{d.model_dump_json(indent=2)}" for i, d in enumerate(drafts)])
    judge_prompt = f"""We need the ultimate golden baseline recipe for '{dish_name}'.
    
Here are 3 independent drafts generated by our baseline recipe AI:

{drafts_text}

INSTRUCTIONS:
1. Analyze the 3 drafts. Identify the most statistically sound, common-sense golden baseline values.
2. If one draft hallucinates a weird ingredient (e.g., cashews in basic dal), ignore it.
3. Average or pick the most credible ingredient weights and portion sizes.
4. Output the final, synthesized golden baseline recipe.
"""
    def run_judge():
        completion = llm_client.beta.chat.completions.parse(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": "You are the head judge of a nutrition AI jury. Synthesize the drafts into one perfect golden baseline recipe."},
                {"role": "user", "content": judge_prompt}
            ],
            response_format=SingleRecipeResponse,
            temperature=0.0
        )
        return completion.choices[0].message.parsed.recipe

    print(f"--- RUNNING JUDGE ---")
    final_recipe = await asyncio.to_thread(run_judge)
    print(f"Final Ingredients: {final_recipe.ingredients_text}")
    print(f"Final Serving: {final_recipe.serving_size}\n")
    
if __name__ == "__main__":
    asyncio.run(run_analysis())
